version: '3'

services:
  node:
    image: satangtech/explorer-node:0.0.1
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_NAME=bitcore
      - BITCORE_CONFIG_PATH=/bitcore/firo.config.json
      - STORAGE_URL=http://storage:5555/contracts/
      - CACHE_URL=http://storage:5555/cache/
    restart: always
    volumes:
      - ./packages/bitcore-node/.env:/bitcore/packages/bitcore-node/.env
      - ./firo.config.json:/bitcore/firo.config.json
    depends_on:
      - db

  db:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - ./.mongo/db:/data/db
      - ./mongo-init-timeseries.js:/docker-entrypoint-initdb.d/mongo-init-timeseries.js:ro
    command: --profile=1 --slowms=20 # for operations that take longer than (ms)
