version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_NAME=bitcore
      - DB_USER=test-user
      - DB_PASS=test-pass
      - DB_PORT=27017
      - BITCORE_CONFIG_PATH=/bitcore/firo-test.config.json
      - STORAGE_URL=http://storage:5555/contracts/
      - CACHE_URL=http://storage:5555/cache/
    restart: always
    volumes:
      - ./packages/bitcore-node/.env:/bitcore/packages/bitcore-node/.env
      - ./firo-test.config.json:/bitcore/firo-test.config.json
    depends_on:
      - init-timeseries
      - storage
      - firovm

  init-timeseries:
    build:
      context: .
      dockerfile: Dockerfile.timeseries
    environment:
      - DB_HOST=db
      - DB_NAME=bitcore
      - DB_USER=test-user
      - DB_PASS=test-pass
      - DB_PORT=27017
    depends_on:
      - db

  storage:
    build:
      context: .
      dockerfile: Dockerfile.storage
    restart: always
    environment:
      - PORT=5555
      - BIND=0.0.0.0
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./service-storage/.env:/service-storage/.env
    depends_on:
      - redis

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=Password123!
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 512mb

  db:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root-user
      - MONGO_INITDB_ROOT_PASSWORD=root-pass
      - MONGO_INITDB_DATABASE=bitcore
    command: --profile=1 --slowms=20 # for operations that take longer than (ms)
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  firovm:
    image: satangtech/firovm-poa:4e0cb5d3019b081d1cd696b4f1bfa709ff5257d2
    tty: true
    stdin_open: true
    working_dir: /root
    command: bash -c "tar xfv firovm.tar && firovmd"
    volumes:
      - ./firovm.tar:/root/firovm.tar
    ports:
      - 1234:1234
      - 11000:11000

  it-test:
    build:
      context: .
      dockerfile: Dockerfile.integration-test
    tty: true
    stdin_open: true
