version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_NAME=bitcore-test
      - BITCORE_CONFIG_PATH=/bitcore/firo.config.json
    platform: linux/amd64
    command: npm run node
    tty: true
    restart: always
    volumes:
      - ./packages/bitcore-node/src:/bitcore/packages/bitcore-node/src
      - ./packages/bitcore-node/test:/bitcore/packages/bitcore-node/test
      - ./firo.config.json:/bitcore/firo.config.json
    depends_on:
      - db

  storage:
    image: node:18-alpine3.14
    restart: always
    command: sh -c "npm i && npm run  build && npm run start"
    stdin_open: true
    tty: true
    ports:
      - 5555:5555
    environment:
      - GOOGLE_KEY=/service-storage/gg-key.json
      - GOOGLE_BUCKET=explorer-code-upload
      - PORT=5555
      - REDIS_URL=redis://192.168.2.37:6379
      - REDIS_PASSWORD=Password123!
    working_dir: /service-storage
    volumes:
      - ./service-storage:/service-storage
      - ./service-storage/contracts:/service-storage/contracts

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./.mongo/db:/data/db
