version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_NAME=bitcore
      - BITCORE_CONFIG_PATH=/bitcore/firo.config.json
      - STORAGE_URL=http://storage:5555/contracts/
      - CACHE_URL=http://storage:5555/cache/
    restart: always
    volumes:
      - ./packages/bitcore-node/.env:/bitcore/packages/bitcore-node/.env
      - ./firo.config.json:/bitcore/firo.config.json
    depends_on:
      - init-timeseries
      - storage

  init-timeseries:
    build:
      context: .
      dockerfile: Dockerfile.timeseries
    depends_on:
      - db

  storage:
    build:
      context: .
      dockerfile: Dockerfile.storage
    restart: always
    environment:
      - PORT=5555
      - BIND=0.0.0.0
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./service-storage/.env:/service-storage/.env
    ports:
      - 5555:5555
    depends_on:
      - redis

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=Password123!
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    volumes:
      - ./redis-persistence:/bitnami/redis/data
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 512mb
    ports:
      - 6379:6379

  db:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - ./.mongo/db:/data/db
    command: --profile=1 --slowms=20 # for operations that take longer than (ms)
